### ISSUE TITLE
gen_data

### ISSUE THREAD

**Issue by afrahshafquat** [cagatayyildiz/npde#2]
Hello, I am trying to understand whats the format of the input data to the algorithm npde_fit from gen_data. Please let me know if I understand this correctly:

* x0 = the  number of observations(rows) x the initial values of latent states(columns) [e.g. dimensions: 5x2]?
* t = the number of observations(rows) x the time series data(columns) [e.g. dimensions: 5x30]
* Y = number of observations(1st dim) x observed values(2 dim) x latent states (3 dimension) [e.g. dimensions: 5x30x2]
* X = true values(rows) x latent states (columns) [e.g. dimensions: 30x2]

If I understand this correctly, then do you think it is possible to still make an inference from a dataset that has following dimensions:

* x0 = 1x2, t = 1x10000, Y=1x10000x1000 X=10000x1000

The main concern I have here is how the method may perform because the number of observations is 1 i.e. a single snapshot, do you think reasonable inference can still be made? Moreover do you think the dimensions of X/Y would impact the inference as well. Any insight in this matter would be highly appreciated! Thanks again for your help!

**Comment by cagatayyildiz** [comment]
Hi,

Your understanding is correct. In general, my notation goes like

 - x0: [N,q].    # num. time series & state dim.
 - t:    [N,T]     # num. time series & seq. length
 - Y:   [N,T,q]

You may or may not have X, i.e., the true trajectory may not be available. We assume it's unknown and only use it for plotting purposes.

If you have a single sequence, then this model should still work (note that your x0 should be 1x1000). However, sparse GPs are not suitable for that many dimensional data. So, I'd definitely give it a try with tons of inducing points, e.g., 2500.

**Comment by afrahshafquat** [comment]
Ok perfect! thanks for getting back about this and for your insight. For inducing points =2500, and states =1000, I would have to set W=2.5 right? to confirm thats the way to change the number of inducing points.
