### ISSUE TITLE
Dimensionality of the kernel

### ISSUE THREAD

**Issue by XinyiYS** [cagatayyildiz/npde#7]
Great repo! Hope you would be able to help me out here.

The dimension of the output of the `K(self, X,X2=None)` operation in `kernels.py` seems to be $M$ by $M$, where $M$ is the size of $X$. However, as the function is vector-valued and thus the kernel should also be vector-valued, I was expecting the output to be $MD$ by $MD$ where $D$ is the dimension of the vector output, following Equ.(8) in the paper and the description again in Section 2.1

A subsequent and more relevant question to my application, is that how to compute the entropy from the kernel representing the posterior? For the scalar-valued GP, one would need to add the learnt noise variance $\sigma^2$ to the covariance matrix/kernel:
$$K(X,X) + \sigma^2 \mathbf{I}\ .$$
However, here the noise variance $\sigma_d^2|_{d=1}^D$ has $D$ dimensions, and according to Equ.(9) in Alvarez et al. (2012), one needs the $MD$ by $MD$ kernel.

Thank you!

**Comment by cagatayyildiz** [comment]
This is true, the covariance matrix is $MD \times MD$. We assume an $M \times M$ block diagonal matrix where each block is $k (\mathbf{x}_i,\mathbf{x}_k) \cdot I_d $. 

I'm not sure of the second part of the question (computing the entropy). Can you elaborate?

**Comment by XinyiYS** [comment]
Thanks for the prompt response!

So in the implementation the $MD\times MD$ is simplified to $M\times M$? Because as I print out the shape of for instance `Kzz()` in `npde.py`, the displayed dimension is $M,M$.

Sure, let me point to the referenced equation (Equation (9) in Alvarez et al. (2012)) reproduced here:

![Screenshot from 2022-09-19 17-39-59](https://user-images.githubusercontent.com/17292375/191124532-0f957ff4-a5eb-4072-87f2-df557158f792.png)

As you can see $\Sigma$ is a diagonal matrix with $D$ diagonal entries as $\{\sigma_d^2\}$. My question is, I want to compute the covariance matrix in the last line of the equation but am having trouble to. In particular, the boldfonted $\mathbf{\Sigma}$ is the kronecker product between $\Sigma$ and $\mathbf{I}$, and as a result $\mathbf{\Sigma}$ has dimension $MD \times MD$. The $\mathbf{K}(\mathbf{X}, \mathbf{X})$, to be added to this covariance must match the dimension for the addition, which brings me to my initial question, how can I obtain a `Kzz()` which has dimension $MD \times MD$?

**Comment by cagatayyildiz** [comment]
In our formulation, $\Sigma$ is also a diagonal matrix with the same entry $\sigma$ on the diagonal. This means, for each output dimension $d \in \{1,\ldots,D}$, we have the same variance. Consequently, the same $M \times M$ matrix $K(Z,Z)$ applies to each output dimension and we never have to compute the whole $MD \times MD$ Kronecker product. Unfortunately, our base implementation only stores $M\times D$ inducing values/outputs $U,Z$ and computes $M\times M$ covariances whereas (if I understood correctly) you need $MD$-dimensional inducing values/outputs and $MD\times MD$ covariances. 

Can you check `kern.OperatorKernel`? I think it matches what you need whereas I don't remember testing this module. So unfortunately I cannot guarantee that it is flawless...

**Comment by XinyiYS** [comment]
> Consequently, the same $M\times M$ matrix $K(Z,Z)$ applies to each output dimension and ...

So, is $\Sigma$ explicitly used in some matrix operation, since I am not sure how. 

To simplify, is there a way to do things in the $M\times M$ size: i.e., calculating the covariance in the last line of Equation (8) above, but in the $M\times M$ shape? I am okay with using that, but not sure how $\Sigma$ would fit in with the current implementation in terms of matrix operation (addition and multiplication).

**Comment by cagatayyildiz** [comment]
We never explicitly form a $D\times D$ kernel matrix but always work with $M \times M$ kernels between $z_i$ and $z_j$ or (similarly $N \times M$ kernels between $x_i$ and $z_i$). You can see the details here: https://github.com/cagatayyildiz/npde/blob/master/npde.py#L62 

Do you refer to including GP uncertainty in the predictions, which is what the last line of equation 8 corresponds to? If so, notice that we discard the GP uncertainty in this work. Check our follow-up work concerning how to properly sample from GP posteriors: https://github.com/hegdepashupati/gaussian-process-odes

**Comment by XinyiYS** [comment]
I see.

> Do you refer to including GP uncertainty in the predictions, which is what the last line of equation 8 corresponds to?

I guess you could say I am trying to include GP uncertainty (i.e., $\Sigma$ or $\mathbf{\Sigma}$), but not for prediction though, because I plan to use the posterior covariance $\mathbf{K}$ for calculating posterior entropy (i.e.,  $\mathbf{K}(\mathbf T, \mathbf T)$ over a set $\mathbf T$ of test input points). I realize you might also call this predictive uncertainty (i.e. used for predictions).

**Comment by cagatayyildiz** [comment]
That, unfortunately you need to implement on your own. Happy to help if you have further questions!

**Comment by XinyiYS** [comment]
Got you, thanks! Closing this issue.
